#!/usr/bin/python3

ship_key_to_size_dict = {
    "battleship": "battleship", 
    "colossus": "colossus", 
    "frigate": "frigate", 
    "corvette": "corvette", 
    "crisis_corvette": "crisis_corvette", 
    "crisis_destroyer": "crisis_destroyer", 
    "crisis_cruiser": "crisis_cruiser", 
    "star_eater": "star_eater", 
    "cruiser": "cruiser", 
    "destroyer": "destroyer", 
    "eventship_04": "eventship_04", 
    "leviathan_01_scavenger_bot": "leviathan_01_scavenger_bot", 
    "leviathan_01_elder_tiyanki": "leviathan_01_elder_tiyanki", 
    "leviathan_01_voidspawn": "leviathan_01_voidspawn", 
    "juggernaut": "juggernaut", 
    "space_dragon_red": "space_dragon_red", 
    "stellarite": "stellarite", 
    "npc_warship_01": "npc_warship_01", 
    "dimensional_horror": "dimensional_horror", 
    "toxic_god": "toxic_god", 
    "sphere": "sphere", 
    "galleon": "galleon", 
    "wraith_01_blue": "wraith_01_blue", 
    "wraith_01_red": "wraith_01_red", 
    "wraith_01_yellow": "wraith_01_yellow", 
    "space_dragon_blue": "space_dragon_blue", 
    "military_station_small": "military_station_small", 
    "military_station_medium": "military_station_medium", 
    "military_station_large": "military_station_large", 
    "ion_cannon": "ion_cannon", 
    "offspring_corvette": "offspring_corvette", 
    "offspring_destroyer": "offspring_destroyer", 
    "offspring_cruiser": "offspring_cruiser", 
    "offspring_battleship": "offspring_battleship", 
    "titan": "titan", 
    "fe_escort": "fe_escort", 
    "fe_escort_o": "fe_escort", 
    "fe_escort_oe": "fe_escort", 
    "fe_battlecruiser": "fe_battlecruiser", 
    "fe_battlecruiser_o": "fe_battlecruiser", 
    "fe_battlecruiser_oe": "fe_battlecruiser", 
    "fe_titan": "fe_titan", 
    "fe_titan_o": "fe_titan", 
    "fe_titan_oe": "fe_titan", 
    "fe_small_station": "fe_small_station", 
    "fe_large_station": "fe_large_station", 
    "fe_goliath": "fe_goliath", 
    "precursor_escort": "precursor_escort", 
    "alpha_precursor_escort": "precursor_escort", 
    "stellar_precursor_escort": "precursor_escort", 
    "phanon_precursor_escort": "precursor_escort", 
    "omega_precursor_escort": "precursor_escort", 
    "precursor_battlecruiser": "precursor_battlecruiser", 
    "alpha_precursor_battlecruiser": "precursor_battlecruiser", 
    "stellar_precursor_battlecruiser": "precursor_battlecruiser", 
    "phanon_precursor_battlecruiser": "precursor_battlecruiser", 
    "omega_precursor_battlecruiser": "precursor_battlecruiser", 
    "precursor_titan": "precursor_titan", 
    "alpha_precursor_titan": "precursor_titan", 
    "sigma_precursor_titan": "precursor_titan", 
    "phanon_precursor_titan": "precursor_titan", 
    "omega_precursor_titan": "precursor_titan", 
    "precursor_assault_carrier": "precursor_assault_carrier", 
    "alpha_precursor_assault_carrier": "precursor_assault_carrier", 
    "stellar_precursor_assault_carrier": "precursor_assault_carrier", 
    "phanon_precursor_assault_carrier": "precursor_assault_carrier", 
    "omega_precursor_assault_carrier": "precursor_assault_carrier"
}

fits_on_slot_dict = {
    "battleship": ["bow", "mid", "stern"], 
    "colossus": ["ship"], 
    "frigate": ["mid"], 
    "corvette": ["mid"], 
    "crisis_corvette": ["mid"], 
    "crisis_destroyer": ["mid"], 
    "crisis_cruiser": ["mid"], 
    "star_eater": ["mid"], 
    "cruiser": ["bow", "mid", "stern"], 
    "destroyer": ["bow", "stern"], 
    "eventship_04": ["mid"], 
    "leviathan_01_scavenger_bot": ["mid"], 
    "leviathan_01_elder_tiyanki": ["mid"], 
    "leviathan_01_voidspawn": ["mid"], 
    "juggernaut": ["core"], 
    "space_dragon_red": ["mid"], 
    "stellarite": ["mid"], 
    "npc_warship_01": ["mid"], 
    "dimensional_horror": ["mid"], 
    "toxic_god": ["mid"], 
    "sphere": ["mid"], 
    "galleon": ["mid"], 
    "wraith_01_blue": ["mid"], 
    "wraith_01_red": ["mid"], 
    "wraith_01_yellow": ["mid"], 
    "space_dragon_blue": ["mid"], 
    "military_station_small": ["north", "west", "east", "south"], 
    "military_station_medium": ["north", "west", "east", "south"], 
    "military_station_large": ["north", "west", "east", "south"], 
    "ion_cannon": ["ship"], 
    "offspring_corvette": ["mid"], 
    "offspring_destroyer": ["bow", "stern"], 
    "offspring_cruiser": ["bow", "mid", "stern"], 
    "offspring_battleship": ["bow", "mid", "stern"], 
    "titan": ["bow", "mid", "stern"], 
    "fe_escort": ["bow", "mid", "stern"], 
    "fe_battlecruiser": ["bow", "mid", "stern"], 
    "fe_titan": ["bow", "mid", "hangar", "stern"], 
    "fe_small_station": ["heavy", "medium"], 
    "fe_large_station": ["xl", "heavy", "medium", "pd"], 
    "fe_goliath": ["bow", "mid", "hangar", "stern"], 
    "precursor_escort": ["bow", "mid", "stern"], 
    "precursor_battlecruiser": ["bow", "mid", "stern"], 
    "precursor_titan": ["spinal", "mid", "core", "stern"], 
    "precursor_assault_carrier": ["spinal", "hanger1", "hanger2", "hanger3"]
}

entity_dict = {
    "battleship": {
        "bow": ["battleship_bow_L1M1S2_entity", "battleship_bow_L2_entity", "battleship_bow_M1S2SHB_entity", "battleship_bow_XL1_entity"], 
        "mid": ["battleship_mid_L2M2_entity", "battleship_mid_L3_entity", "battleship_mid_M4SHB_entity", "battleship_mid_S4LHB_entity"], 
        "stern": ["battleship_stern_L1_entity", "battleship_stern_M2_entity"]}, 
    "colossus": {"ship": ["colossus_ship_entity"]}, 
    "frigate": {"mid": ["corvette_M1S1_entity", "corvette_S3_entity"]}, 
    "corvette": {"mid": ["corvette_M1S1_entity", "corvette_S3_entity"]}, 
    "crisis_corvette": {"mid": ["crisis_corvette_M1S1_entity", "crisis_corvette_S3_entity"]}, 
    "crisis_destroyer": {"mid": ["crisis_destroyer_1M2S1M_entity", "crisis_destroyer_1L2S_entity"]}, 
    "crisis_cruiser": {"mid": ["crisis_cruiser_hull_entity"]}, 
    "star_eater": {"mid": ["star_eater_ship_entity"]}, 
    "cruiser": {
        "bow": ["cruiser_bow_L1_entity", "cruiser_bow_M1S2_entity", "cruiser_bow_M2_entity"], 
        "mid": ["cruiser_mid_S2HB_entity", "cruiser_mid_L1M1_entity", "cruiser_mid_M3_entity", "cruiser_mid_M2S2_entity"], 
        "stern": ["cruiser_stern_M1_entity", "cruiser_stern_S2_entity"]}, 
    "destroyer": {
        "bow": ["destroyer_bow_M1S2_entity", "destroyer_bow_S3_entity", "destroyer_bow_L1_entity"], 
        "stern": ["destroyer_stern_S2_entity", "destroyer_stern_M1_entity"]}, 
    "juggernaut": {"core": ["juggernaut_core_section_entity"]}, 
    "military_station_small": {
        "north": ["military_station_section_light_entity", "military_station_section_medium_entity", "military_station_section_heavy_entity", "military_station_section_hangar_entity"], 
        "west": ["military_station_section_light_entity", "military_station_section_medium_entity", "military_station_section_heavy_entity", "military_station_section_hangar_entity"], 
        "east": ["military_station_section_light_entity", "military_station_section_medium_entity", "military_station_section_heavy_entity", "military_station_section_hangar_entity"], 
        "south": ["military_station_section_light_entity", "military_station_section_medium_entity", "military_station_section_heavy_entity", "military_station_section_hangar_entity"]}, 
    "military_station_medium": {
        "north": ["military_station_section_light_entity", "military_station_section_medium_entity", "military_station_section_heavy_entity", "military_station_section_hangar_entity"], 
        "west": ["military_station_section_light_entity", "military_station_section_medium_entity", "military_station_section_heavy_entity", "military_station_section_hangar_entity"], 
        "east": ["military_station_section_light_entity", "military_station_section_medium_entity", "military_station_section_heavy_entity", "military_station_section_hangar_entity"], 
        "south": ["military_station_section_light_entity", "military_station_section_medium_entity", "military_station_section_heavy_entity", "military_station_section_hangar_entity"]}, 
    "military_station_large": {
        "north": ["military_station_section_light_entity", "military_station_section_medium_entity", "military_station_section_heavy_entity", "military_station_section_hangar_entity"], 
        "west": ["military_station_section_light_entity", "military_station_section_medium_entity", "military_station_section_heavy_entity", "military_station_section_hangar_entity"], 
        "east": ["military_station_section_light_entity", "military_station_section_medium_entity", "military_station_section_heavy_entity", "military_station_section_hangar_entity"], 
        "south": ["military_station_section_light_entity", "military_station_section_medium_entity", "military_station_section_heavy_entity", "military_station_section_hangar_entity"]}, 
    "ion_cannon": {"ship": ["ion_cannon_section_entity"]}, 
    "offspring_corvette": {"mid": ["corvette_M1S1_entity", "corvette_S3_entity"]}, 
    "offspring_destroyer": {
        "bow": ["destroyer_bow_M1S2_entity", "destroyer_bow_S3_entity", "destroyer_bow_L1_entity"], 
        "stern": ["destroyer_stern_S2_entity", "destroyer_stern_M1_entity"]}, 
    "offspring_cruiser": {
        "bow": ["cruiser_bow_L1_entity", "cruiser_bow_M1S2_entity", "cruiser_bow_M2_entity"], 
        "mid": ["cruiser_mid_S2HB_entity", "cruiser_mid_L1M1_entity", "cruiser_mid_M3_entity", "cruiser_mid_M2S2_entity"], 
        "stern": ["cruiser_stern_M1_entity", "cruiser_stern_S2_entity"]}, 
    "offspring_battleship": {
        "bow": ["battleship_bow_L1M1S2_entity", "battleship_bow_L2_entity", "battleship_bow_M1S2SHB_entity", "battleship_bow_XL1_entity"], 
        "mid": ["battleship_mid_L2M2_entity", "battleship_mid_L3_entity", "battleship_mid_M4SHB_entity", "battleship_mid_S4LHB_entity"], 
        "stern": ["battleship_stern_L1_entity", "battleship_stern_M2_entity"]}, 
    "titan": {
        "bow": ["titan_bow_entity"], 
        "mid": ["titan_mid_entity"], 
        "stern": ["titan_stern_entity"]}, 
    "fe_escort": {
        "bow": ["fe_escort_bow_entity"], 
        "mid": ["fe_escort_stern_entity"], 
        "stern": ["fe_escort_stern_entity"]}, 
    "fe_escort_o": {
        "bow": ["fe_escort_bow_entity"], 
        "mid": ["fe_escort_stern_entity"], 
        "stern": ["fe_escort_stern_entity"]}, 
    "fe_escort_oe": {
        "bow": ["fe_escort_bow_entity"], 
        "mid": ["fe_escort_stern_entity"], 
        "stern": ["fe_escort_stern_entity"]}, 
    "fe_battlecruiser": {
        "bow": ["fe_battlecruiser_bow_entity"], 
        "mid": ["fe_battlecruiser_mid_entity"], 
        "stern": ["fe_battlecruiser_stern_entity"]}, 
    "fe_battlecruiser_o": {
        "bow": ["fe_battlecruiser_bow_entity"], 
        "mid": ["fe_battlecruiser_mid_entity"], 
        "stern": ["fe_battlecruiser_stern_entity"]}, 
    "fe_battlecruiser_oe": {
        "bow": ["fe_battlecruiser_bow_entity"], 
        "mid": ["fe_battlecruiser_mid_entity"], 
        "stern": ["fe_battlecruiser_stern_entity"]}, 
    "fe_titan": {
        "bow": ["fe_titan_bow_entity"], 
        "mid": ["fe_titan_mid_entity"], 
        "hangar": ["fe_titan_hangar_entity"], 
        "stern": ["fe_titan_stern_entity"]}, 
    "fe_titan_o": {
        "bow": ["fe_titan_bow_entity"], 
        "mid": ["fe_titan_mid_entity"], 
        "hangar": ["fe_titan_hangar_entity"], 
        "stern": ["fe_titan_stern_entity"]}, 
    "fe_titan_oe": {
        "bow": ["fe_titan_bow_entity"], 
        "mid": ["fe_titan_mid_entity"], 
        "hangar": ["fe_titan_hangar_entity"], 
        "stern": ["fe_titan_stern_entity"]}, 
    "fe_small_station": {
        "heavy": ["fe_small_station_heavy_entity"], 
        "medium": ["fe_small_station_medium_entity"]}, 
    "fe_large_station": {
        "xl": ["fe_large_station_xl_entity"], 
        "heavy": ["fe_large_station_heavy_entity"], 
        "medium": ["fe_large_station_medium_entity"], 
        "pd": ["fe_large_station_pd_entity"]}, 
    "fe_goliath": {
        "bow": ["fe_goliath_bow_entity"], 
        "mid": ["fe_goliath_mid_entity"], 
        "hangar": ["fe_goliath_hangar_entity"], 
        "stern": ["fe_goliath_stern_entity"]}, 
    "precursor_escort": {
        "bow": ["precursor_escort_bow_entity"], 
        "mid": ["precursor_escort_stern_entity"], 
        "stern": ["precursor_escort_stern_entity"]}, 
    "alpha_precursor_escort": {
        "bow": ["alpha_precursor_escort_bow_entity"], 
        "mid": ["precursor_escort_stern_entity"], 
        "stern": ["precursor_escort_stern_entity"]}, 
    "stellar_precursor_escort": {
        "bow": ["stellar_precursor_escort_bow_entity"], 
        "mid": ["precursor_escort_stern_entity"], 
        "stern": ["precursor_escort_stern_entity"]}, 
    "phanon_precursor_escort": {
        "bow": ["phanon_precursor_escort_bow_entity"], 
        "mid": ["precursor_escort_stern_entity"], 
        "stern": ["precursor_escort_stern_entity"]}, 
    "omega_precursor_escort": {
        "bow": ["omega_precursor_escort_bow_entity"], 
        "mid": ["precursor_escort_stern_entity"], 
        "stern": ["precursor_escort_stern_entity"]}, 
    "precursor_battlecruiser": {
        "bow": ["precursor_battlecruiser_mid_entity"], 
        "mid": ["precursor_battlecruiser_stern_entity"], 
        "stern": ["precursor_battlecruiser_stern_entity"]}, 
    "alpha_precursor_battlecruiser": {
        "bow": ["alpha_precursor_battlecruiser_mid_entity"], 
        "mid": ["precursor_battlecruiser_stern_entity"], 
        "stern": ["precursor_battlecruiser_stern_entity"]}, 
    "stellar_precursor_battlecruiser": {
        "bow": ["stellar_precursor_battlecruiser_mid_entity"], 
        "mid": ["precursor_battlecruiser_stern_entity"], 
        "stern": ["precursor_battlecruiser_stern_entity"]}, 
    "phanon_precursor_battlecruiser": {
        "bow": ["phanon_precursor_battlecruiser_mid_entity"], 
        "mid": ["precursor_battlecruiser_stern_entity"], 
        "stern": ["precursor_battlecruiser_stern_entity"]}, 
    "omega_precursor_battlecruiser": {
        "bow": ["omega_precursor_battlecruiser_mid_entity"], 
        "mid": ["precursor_battlecruiser_stern_entity"], 
        "stern": ["precursor_battlecruiser_stern_entity"]}, 
    "precursor_titan": {
        "spinal": ["precursor_titan_mid_entity"], 
        "mid": ["precursor_titan_stern_entity"], 
        "core": ["precursor_titan_stern_entity"], 
        "stern": ["precursor_titan_stern_entity"]}, 
    "alpha_precursor_titan": {
        "spinal": ["alpha_precursor_titan_mid_entity"], 
        "mid": ["precursor_titan_stern_entity"], 
        "core": ["precursor_titan_stern_entity"], 
        "stern": ["precursor_titan_stern_entity"]}, 
    "sigma_precursor_titan": {
        "spinal": ["stellar_precursor_titan_mid_entity"], 
        "mid": ["precursor_titan_stern_entity"], 
        "core": ["precursor_titan_stern_entity"], 
        "stern": ["precursor_titan_stern_entity"]}, 
    "phanon_precursor_titan": {
        "spinal": ["phanon_precursor_titan_mid_entity"], 
        "mid": ["precursor_titan_stern_entity"], 
        "core": ["precursor_titan_stern_entity"], 
        "stern": ["precursor_titan_stern_entity"]}, 
    "omega_precursor_titan": {
        "spinal": ["omega_precursor_titan_mid_entity"], 
        "mid": ["precursor_titan_stern_entity"], 
        "core": ["precursor_titan_stern_entity"], 
        "stern": ["precursor_titan_stern_entity"]}, 
    "precursor_assault_carrier": {
        "spinal": ["precursor_assault_carrier_spinal_entity"], 
        "hanger1": ["precursor_assault_carrier_hanger1_entity"], 
        "hanger2": ["precursor_assault_carrier_hanger1_entity"], 
        "hanger3": ["precursor_assault_carrier_hanger1_entity"]}, 
    "alpha_precursor_assault_carrier": {
        "spinal": ["alpha_precursor_assault_carrier_spinal_entity"], 
        "hanger1": ["precursor_assault_carrier_hanger1_entity"], 
        "hanger2": ["precursor_assault_carrier_hanger1_entity"], 
        "hanger3": ["precursor_assault_carrier_hanger1_entity"]}, 
    "stellar_precursor_assault_carrier": {
        "spinal": ["stellar_precursor_assault_carrier_spinal_entity"], 
        "hanger1": ["precursor_assault_carrier_hanger1_entity"], 
        "hanger2": ["precursor_assault_carrier_hanger1_entity"], 
        "hanger3": ["precursor_assault_carrier_hanger1_entity"]}, 
    "phanon_precursor_assault_carrier": {
        "spinal": ["phanon_precursor_assault_carrier_spinal_entity"], 
        "hanger1": ["precursor_assault_carrier_hanger1_entity"], 
        "hanger2": ["precursor_assault_carrier_hanger1_entity"], 
        "hanger3": ["precursor_assault_carrier_hanger1_entity"]}, 
    "omega_precursor_assault_carrier": {
        "spinal": ["omega_precursor_assault_carrier_spinal_entity"], 
        "hanger1": ["precursor_assault_carrier_hanger1_entity"], 
        "hanger2": ["precursor_assault_carrier_hanger1_entity"], 
        "hanger3": ["precursor_assault_carrier_hanger1_entity"]}
}

entity_locator_dict = {
    "battleship_bow_L1M1S2_entity": {"L": 1, "M": 1, "S": 2}, 
    "battleship_bow_L2_entity": {"L": 2}, 
    "battleship_bow_M1S2SHB_entity": {"HB": 1, "M": 1, "S": 2}, 
    "battleship_bow_XL1_entity": {"X": 1}, 
    "battleship_mid_L2M2_entity": {"L": 2, "M": 2}, 
    "battleship_mid_L3_entity": {"L": 3}, 
    "battleship_mid_M4SHB_entity": {"HB": 1, "M": 4}, 
    "battleship_mid_S4LHB_entity": {"HB": 2, "S": 4}, 
    "battleship_stern_L1_entity": {"L": 1}, 
    "battleship_stern_M2_entity": {"M": 2}, 
    "colossus_ship_entity": {"W": 1}, 
    "corvette_M1S1_entity": {"M": 1, "S": 1}, 
    "corvette_S3_entity": {"S": 3}, 
    "crisis_corvette_M1S1_entity": {"M": 1, "S": 1}, 
    "crisis_corvette_S3_entity": {"S": 3}, 
    "crisis_destroyer_1M2S1M_entity": {"M": 2, "S": 2}, 
    "crisis_destroyer_1L2S_entity": {"L": 1, "S": 2}, 
    "crisis_cruiser_hull_entity": {"L": 1, "M": 2, "S": 2}, 
    "star_eater_ship_entity": {"core": 1, "root": 25}, 
    "cruiser_bow_L1_entity": {"L": 1}, 
    "cruiser_bow_M1S2_entity": {"M": 1, "S": 2}, 
    "cruiser_bow_M2_entity": {"M": 2}, 
    "cruiser_mid_S2HB_entity": {"HB": 1, "S": 2}, 
    "cruiser_mid_L1M1_entity": {"L": 1, "M": 1}, 
    "cruiser_mid_M3_entity": {"M": 3}, 
    "cruiser_mid_M2S2_entity": {"M": 2, "S": 2}, 
    "cruiser_stern_M1_entity": {"M": 1}, 
    "cruiser_stern_S2_entity": {"S": 2}, 
    "destroyer_bow_M1S2_entity": {"M": 1, "S": 2}, 
    "destroyer_bow_S3_entity": {"S": 3}, 
    "destroyer_bow_L1_entity": {"L": 1}, 
    "destroyer_stern_S2_entity": {"S": 2}, 
    "destroyer_stern_M1_entity": {"M": 1}, 
    "juggernaut_core_section_entity": {"X": 2, "HB": 6, "M": 5}, 
    "military_station_section_light_entity": {"S": 4}, 
    "military_station_section_medium_entity": {"M": 2}, 
    "military_station_section_heavy_entity": {"L": 1}, 
    "military_station_section_hangar_entity": {"L": 1}, 
    "ion_cannon_section_entity": {"X": 1}, 
    "titan_bow_entity": {"X": 1}, 
    "titan_mid_entity": {"L": 4}, 
    "titan_stern_entity": {"L": 2}, 
    "fe_escort_bow_entity": {"L": 1}, 
    "fe_escort_stern_entity": {"M": 2}, 
    "fe_battlecruiser_bow_entity": {"L": 2}, 
    "fe_battlecruiser_mid_entity": {"L": 2, "M": 4}, 
    "fe_battlecruiser_stern_entity": {"M": 4}, 
    "fe_titan_bow_entity": {"T": 1, "L": 2}, 
    "fe_titan_mid_entity": {"L": 2}, 
    "fe_titan_hangar_entity": {"M": 2}, 
    "fe_titan_stern_entity": {"M": 2}, 
    "fe_small_station_heavy_entity": {"root": 2, "M": 2}, 
    "fe_small_station_medium_entity": {"M": 4}, 
    "fe_large_station_xl_entity": {"root": 2, "L": 2}, 
    "fe_large_station_heavy_entity": {"L": 2, "M": 4}, 
    "fe_large_station_medium_entity": {"M": 4}, 
    "fe_large_station_pd_entity": {"S": 4}, 
    "fe_goliath_bow_entity": {"X": 1, "L": 2}, 
    "fe_goliath_mid_entity": {"M": 4}, 
    "fe_goliath_hangar_entity": {"M": 2}, 
    "fe_goliath_stern_entity": {"M": 4}, 
    "precursor_escort_bow_entity": {"L": 1, "M": 2}, 
    "alpha_precursor_escort_bow_entity": {"L": 1, "M": 2}, 
    "stellar_precursor_escort_bow_entity": {"L": 1, "M": 2}, 
    "phanon_precursor_escort_bow_entity": {"L": 1, "M": 2}, 
    "omega_precursor_escort_bow_entity": {"L": 1, "M": 2}, 
    "precursor_escort_stern_entity": {"M": 2, "S": 2}, 
    "precursor_battlecruiser_mid_entity": {"L": 1, "S": 2}, 
    "alpha_precursor_battlecruiser_mid_entity": {"L": 1, "S": 2}, 
    "stellar_precursor_battlecruiser_mid_entity": {"L": 1, "S": 2}, 
    "phanon_precursor_battlecruiser_mid_entity": {"L": 1, "S": 2}, 
    "omega_precursor_battlecruiser_mid_entity": {"L": 1, "S": 2}, 
    "precursor_battlecruiser_stern_entity": {"L": 1, "M": 4}, 
    "precursor_titan_mid_entity": {"L": 1, "S": 4}, 
    "alpha_precursor_titan_mid_entity": {"L": 1, "S": 4}, 
    "stellar_precursor_titan_mid_entity": {"L": 1, "S": 4}, 
    "phanon_precursor_titan_mid_entity": {"L": 1, "S": 4}, 
    "omega_precursor_titan_mid_entity": {"L": 1, "S": 4}, 
    "precursor_titan_stern_entity": {"M": 8, "S": 4}, 
    "precursor_assault_carrier_spinal_entity": {"X": 1, "L": 2}, 
    "alpha_precursor_assault_carrier_spinal_entity": {"X": 1, "L": 2}, 
    "stellar_precursor_assault_carrier_spinal_entity": {"X": 1, "L": 2}, 
    "phanon_precursor_assault_carrier_spinal_entity": {"X": 1, "L": 2}, 
    "omega_precursor_assault_carrier_spinal_entity": {"X": 1, "L": 2}, 
    "precursor_assault_carrier_hanger1_entity": {"L": 2, "HB": 4}
}

vanilla_section_score_dict = {
    "battleship": {"bow": 20, "mid": 24, "stern": 10}, 
    "colossus": {"ship": 24}, 
    "frigate": {"mid": 9}, 
    "corvette": {"mid": 8}, 
    "crisis_corvette": {"mid": 10}, 
    "crisis_destroyer": {"mid": 16}, 
    "crisis_cruiser": {"mid": 26}, 
    "star_eater": {"mid": 141}, 
    "cruiser": {"bow": 12, "mid": 14, "stern": 8}, 
    "destroyer": {"bow": 10, "stern": 6}, 
    "juggernaut": {"core": 142}, 
    "military_station_small": {"north": 12, "west": 12, "east": 12, "south": 12}, 
    "military_station_medium": {"north": 12, "west": 12, "east": 12, "south": 12}, 
    "military_station_large": {"north": 26, "west": 26, "east": 26, "south": 26}, 
    "ion_cannon": {"ship": 46}, 
    "offspring_corvette": {"mid": 8}, 
    "offspring_destroyer": {"bow": 10, "stern": 6}, 
    "offspring_cruiser": {"bow": 12, "mid": 14, "stern": 8}, 
    "offspring_battleship": {"bow": 20, "mid": 24, "stern": 10}, 
    "titan": {"bow": 40, "mid": 40, "stern": 14}, 
    "fe_escort": {"bow": 8, "mid": 10, "stern": 10}, 
    "fe_escort_o": {"bow": 14, "mid": 18, "stern": 18}, 
    "fe_escort_oe": {"bow": 20, "mid": 30, "stern": 24}, 
    "fe_battlecruiser": {"bow": 32, "mid": 18, "stern": 18}, 
    "fe_battlecruiser_o": {"bow": 46, "mid": 36, "stern": 40}, 
    "fe_battlecruiser_oe": {"bow": 60, "mid": 58, "stern": 62}, 
    "fe_titan": {"bow": 38, "mid": 46, "hangar": 38, "stern": 36}, 
    "fe_titan_o": {"bow": 66, "mid": 62, "hangar": 54, "stern": 46}, 
    "fe_titan_oe": {"bow": 82, "mid": 70, "hangar": 70, "stern": 58}, 
    "fe_small_station": {"heavy": 26, "medium": 22}, 
    "fe_large_station": {"xl": 54, "heavy": 38, "medium": 34, "pd": 26}, 
    "fe_goliath": {"bow": 98, "mid": 70, "hangar": 70, "stern": 70}, 
    "precursor_escort": {"bow": 14, "mid": 8, "stern": 8}, 
    "alpha_precursor_escort": {"bow": 20, "mid": 18, "stern": 18}, 
    "stellar_precursor_escort": {"bow": 24, "mid": 22, "stern": 22}, 
    "phanon_precursor_escort": {"bow": 30, "mid": 28, "stern": 28}, 
    "omega_precursor_escort": {"bow": 30, "mid": 30, "stern": 26}, 
    "precursor_battlecruiser": {"bow": 30, "mid": 30, "stern": 16}, 
    "alpha_precursor_battlecruiser": {"bow": 42, "mid": 42, "stern": 34}, 
    "stellar_precursor_battlecruiser": {"bow": 52, "mid": 50, "stern": 42}, 
    "phanon_precursor_battlecruiser": {"bow": 68, "mid": 66, "stern": 58}, 
    "omega_precursor_battlecruiser": {"bow": 60, "mid": 68, "stern": 62}, 
    "precursor_titan": {"spinal": 46, "mid": 44, "core": 44, "stern": 34}, 
    "alpha_precursor_titan": {"spinal": 72, "mid": 62, "core": 60, "stern": 50}, 
    "stellar_precursor_titan": {"spinal": 80, "mid": 70, "core": 68, "stern": 58}, 
    "phanon_precursor_titan": {"spinal": 104, "mid": 94, "core": 92, "stern": 82}, 
    "omega_precursor_titan": {"spinal": 104, "mid": 86, "core": 86, "stern": 76}, 
    "precursor_assault_carrier": {"spinal": 52, "hanger1": 44, "hanger2": 44, "hanger3": 44}, 
    "alpha_precursor_assault_carrier": {"spinal": 70, "hanger1": 60, "hanger2": 60, "hanger3": 60}, 
    "stellar_precursor_assault_carrier": {"spinal": 78, "hanger1": 70, "hanger2": 70, "hanger3": 70}, 
    "phanon_precursor_assault_carrier": {"spinal": 102, "hanger1": 94, "hanger2": 94, "hanger3": 94}, 
    "omega_precursor_assault_carrier": {"spinal": 94, "hanger1": 86, "hanger2": 86, "hanger3": 86}
}

section_cost_dict = {
    "battleship": {"alloys": 80}, 
    "frigate": {"alloys": 30}, 
    "corvette": {"alloys": 30}, 
    "cruiser": {"alloys": 40}, 
    "destroyer": {"alloys": 30}, 
    "military_station_small": {"alloys": 30}, 
    "military_station_medium": {"alloys": 30}, 
    "offspring_corvette": {"alloys": 30}, 
    "offspring_destroyer": {"alloys": 30}, 
    "offspring_cruiser": {"alloys": 40}, 
    "offspring_battleship": {"alloys": 80}, 
    "titan": {"alloys": 160}, 
    "juggernaut": {"alloys": 960}, 
    "fe_escort": {"alloys": 30}, 
    "fe_escort_o": {"alloys": 60, "sr_living_metal": 6}, 
    "fe_escort_oe": {"alloys": 80, "sr_living_metal": 8}, 
    "fe_battlecruiser": {"alloys": 80}, 
    "fe_battlecruiser_o": {"alloys": 120, "sr_living_metal": 12}, 
    "fe_battlecruiser_oe": {"alloys": 160, "sr_living_metal": 16}, 
    "fe_titan": {"alloys": 160}, 
    "fe_titan_o": {"alloys": 320, "sr_living_metal": 32}, 
    "fe_titan_oe": {"alloys": 440, "sr_living_metal": 44}, 
    "fe_small_station": {"alloys": 30}, 
    "fe_large_station": {"alloys": 80}, 
    "fe_goliath": {"alloys": 360, "sr_living_metal": 36}, 
    "precursor_escort": {"alloys": 20, "sr_dark_matter": 5, "acot_sr_dark_energy": 5}, 
    "alpha_precursor_escort": {"sr_dark_matter": 10, "acot_sr_dark_energy": 10}, 
    "stellar_precursor_escort": {"acot_sr_stellarite": 5, "sr_dark_matter": 15, "acot_sr_dark_energy": 15}, 
    "phanon_precursor_escort": {"alloys": 120}, 
    "omega_precursor_escort": {"acot_sr_light_matter": 10}, 
    "precursor_battlecruiser": {"alloys": 40, "sr_dark_matter": 10, "acot_sr_dark_energy": 10}, 
    "alpha_precursor_battlecruiser": {"sr_dark_matter": 20, "acot_sr_dark_energy": 20}, 
    "stellar_precursor_battlecruiser": {"acot_sr_stellarite": 10, "sr_dark_matter": 30, "acot_sr_dark_energy": 30}, 
    "phanon_precursor_battlecruiser": {"alloys": 240}, 
    "omega_precursor_battlecruiser": {"acot_sr_light_matter": 15}, 
    "precursor_titan": {"alloys": 80, "sr_dark_matter": 20, "acot_sr_dark_energy": 20}, 
    "alpha_precursor_titan": {"sr_dark_matter": 40, "acot_sr_dark_energy": 40}, 
    "stellar_precursor_titan": {"acot_sr_stellarite": 15, "sr_dark_matter": 45, "acot_sr_dark_energy": 45}, 
    "phanon_precursor_titan": {"alloys": 360}, 
    "omega_precursor_titan": {"acot_sr_light_matter": 15}, 
    "precursor_assault_carrier": {"alloys": 80, "sr_dark_matter": 20, "acot_sr_dark_energy": 20}, 
    "alpha_precursor_assault_carrier": {"sr_dark_matter": 40, "acot_sr_dark_energy": 40}, 
    "stellar_precursor_assault_carrier": {"acot_sr_stellarite": 15, "sr_dark_matter": 45, "acot_sr_dark_energy": 45}, 
    "phanon_precursor_assault_carrier": {"alloys": 360}, 
    "omega_precursor_assault_carrier": {"acot_sr_light_matter": 15}
}

component_score_dict = {
    "PD": 1, 
    "S": 1, 
    "US": 1, 
    "G": 2, 
    "M": 2, 
    "AUX": 2, 
    "UM": 2, 
    "L": 4, 
    "UL": 4, 
    "HB": 4, 
    "X": 8, 
    "T": 16, 
    "W": 0
}

component_type_l_simp_chinese = {
    "PD": "点防", 
    "S": "哨卫", 
    "US": "轻甲", 
    "G": "鱼雷", 
    "M": "炮台", 
    "AUX": "辅助", 
    "UM": "重甲", 
    "L": "重炮", 
    "UL": "铁卫", 
    "HB": "舰载机", 
    "X": "轴基", 
    "T": "泰坦", 
    "W": "歼星"
}

component_quantity_l_simp_chinese = {
    1: "", 
    2: "点射", 
    3: "连射", 
    4: "四重", 
    5: "齐射", 
    6: "覆盖", 
    7: "焚烧", 
    8: "炼狱", 
    9: "审判", 
    10: "天灾"
}

ship_size_l_simp_chinese = {
    "battleship": "战列舰", 
    "colossus": "巨像", 
    "frigate": "雷击艇", 
    "corvette": "护卫舰", 
    "crisis_corvette": "威慑级护卫舰", 
    "crisis_destroyer": "威慑级驱逐舰", 
    "crisis_cruiser": "威慑级巡洋舰", 
    "star_eater": "焚天神兵", 
    "cruiser": "巡洋舰", 
    "destroyer": "驱逐舰", 
    "juggernaut": "主宰", 
    "military_station_small": "小型防御平台", 
    "military_station_medium": "中型防御平台", 
    "military_station_large": "重型防御平台", 
    "ion_cannon": "离子加农炮台", 
    "titan": "泰坦", 
    "fe_escort": "护航舰", 
    "fe_escort_o": "先进护航舰", 
    "fe_escort_oe": "始源护航舰", 
    "fe_battlecruiser": "战列巡洋舰", 
    "fe_battlecruiser_o": "先进战列巡洋舰", 
    "fe_battlecruiser_oe": "始源战列巡洋舰", 
    "fe_titan": "失落泰坦", 
    "fe_titan_o": "先进失落泰坦", 
    "fe_titan_oe": "始源失落泰坦", 
    "fe_small_station": "防御前哨", 
    "fe_large_station": "防御塔", 
    "fe_goliath": "歌利亚", 
    "precursor_escort": "先驱者护航舰", 
    "alpha_precursor_escort": "Alpha先驱者护航舰", 
    "stellar_precursor_escort": "Sigma先驱者护航舰", 
    "phanon_precursor_escort": "卓越先驱者护航舰", 
    "omega_precursor_escort": "Omega先驱者护航舰", 
    "precursor_battlecruiser": "先驱者战列巡洋舰", 
    "alpha_precursor_battlecruiser": "Alpha先驱者战列巡洋舰", 
    "stellar_precursor_battlecruiser": "Sigma先驱者战列巡洋舰", 
    "phanon_precursor_battlecruiser": "卓越先驱者战列巡洋舰", 
    "omega_precursor_battlecruiser": "Omega先驱者战列巡洋舰", 
    "precursor_titan": "先驱者泰坦", 
    "alpha_precursor_titan": "Alpha先驱者泰坦", 
    "stellar_precursor_titan": "Sigma先驱者泰坦", 
    "phanon_precursor_titan": "卓越先驱者泰坦", 
    "omega_precursor_titan": "Omega先驱者泰坦", 
    "precursor_assault_carrier": "先驱者攻击舰", 
    "alpha_precursor_assault_carrier": "Alpha先驱者攻击舰", 
    "stellar_precursor_assault_carrier": "Sigma先驱者攻击舰", 
    "phanon_precursor_assault_carrier": "卓越先驱者攻击舰", 
    "omega_precursor_assault_carrier": "Omega先驱者攻击舰"
}

slot_l_simp_chinese = {
    "bow": "舰艏", 
    "mid": "舰体", 
    "stern": "舰艉", 
    "hangar": "机库", 
    "north": "区段", 
    "west": "区段", 
    "east": "区段", 
    "south": "区段", 
    "ship": "战舰", 
    "core": "核心", 
    "heavy": "重型区段", 
    "medium": "中型区段", 
    "xl": "巨型区段", 
    "pd": "点防区段", 
    "spinal": "中枢", 
    "hanger1": "机库", 
    "hanger2": "机库", 
    "hanger3": "机库"
}

component_type_l_english = {
    "PD": "Point Defense ", 
    "S": "Sentinel ", 
    "US": "Spardeck ", 
    "G": "Torpedo ", 
    "M": "Turret ", 
    "AUX": "Assistant ", 
    "UM": "Harmor ", 
    "L": "Artillery ", 
    "UL": "Iron Armor ", 
    "HB": "Aircraft ", 
    "X": "Axial ", 
    "T": "Titan ", 
    "W": "Star Destroyer "
}

component_quantity_l_english = {
    1: "", 
    2: "Burst ", 
    3: "Dartle ", 
    4: "Quad ", 
    5: "Volley ", 
    6: "Coverage ", 
    7: "Incineration ", 
    8: "Purgatory ", 
    9: "Judge ", 
    10: "Crisis "
}

ship_size_l_english = {
    "battleship": "Battleship ", 
    "colossus": "Colossus ", 
    "frigate": "Frigate ", 
    "corvette": "Corvette ", 
    "crisis_corvette": "Crisis Corvette ", 
    "crisis_destroyer": "Crisis Destroyer ", 
    "crisis_cruiser": "Crisis Cruiser ", 
    "star_eater": "Star Eater ", 
    "cruiser": "Cruiser ", 
    "destroyer": "Destroyer ", 
    "juggernaut": "Juggernaut ", 
    "military_station_small": "Small Military Station ", 
    "military_station_medium": "Medium Military Station ", 
    "military_station_large": "Large Military Station ", 
    "ion_cannon": "Ion Cannon ", 
    "titan": "Titan ", 
    "fe_escort": "Escort ", 
    "fe_escort_o": "Advanced Escort ", 
    "fe_escort_oe": "Origin Escort ", 
    "fe_battlecruiser": "Battlecruiser ", 
    "fe_battlecruiser_o": "Advanced Battlecruiser ", 
    "fe_battlecruiser_oe": "Origin Battlecruiser ", 
    "fe_titan": "Fallen Titan ", 
    "fe_titan_o": "Advanced Fallen Titan ", 
    "fe_titan_oe": "Origin Fallen Titan ", 
    "fe_small_station": "Defense Outpost ", 
    "fe_large_station": "Defense Tower ", 
    "fe_goliath": "Goliath ", 
    "precursor_escort": "Precursor Escort", 
    "alpha_precursor_escort": "Alpha Precursor Escort", 
    "stellar_precursor_escort": "Sigma Precursor Escort", 
    "phanon_precursor_escort": "Phanon Precursor Escort", 
    "omega_precursor_escort": "Omega Precursor Escort", 
    "precursor_battlecruiser": "Precursor Battlecruiser", 
    "alpha_precursor_battlecruiser": "Alpha Precursor Battlecruiser", 
    "stellar_precursor_battlecruiser": "Sigma Precursor Battlecruiser", 
    "phanon_precursor_battlecruiser": "Phanon Precursor Battlecruiser", 
    "omega_precursor_battlecruiser": "Omega Precursor Battlecruiser", 
    "precursor_titan": "Precursor Titan", 
    "alpha_precursor_titan": "Alpha Precursor Titan", 
    "stellar_precursor_titan": "Sigma Precursor Titan", 
    "phanon_precursor_titan": "Phanon Precursor Titan", 
    "omega_precursor_titan": "Omega Precursor Titan", 
    "precursor_assault_carrier": "Precursor Assault Carrier", 
    "alpha_precursor_assault_carrier": "Alpha Precursor Assault Carrier", 
    "stellar_precursor_assault_carrier": "Sigma Precursor Assault Carrier", 
    "phanon_precursor_assault_carrier": "Phanon Precursor Assault Carrier", 
    "omega_precursor_assault_carrier": "Omega Precursor Assault Carrier"
}

slot_l_english = {
    "bow": "Bow", 
    "mid": "Hull", 
    "stern": "Stern", 
    "hangar": "hangar", 
    "north": "Section", 
    "west": "Section", 
    "east": "Section", 
    "south": "Section", 
    "ship": "Warship", 
    "core": "Core", 
    "heavy": "Heavy Section", 
    "medium": "Medium Section", 
    "xl": "Ultimate Section", 
    "pd": "Point-Defense Section", 
    "spinal": "Spinal", 
    "hanger1": "Hangar", 
    "hanger2": "Hangar", 
    "hanger3": "Hangar"
}